source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.4'
gem 'pry'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.7', '>= 6.1.7.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 6.4.0'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'google-protobuf', '~> 3.22.2'
gem 'grpc', '~> 1.49.1'
gem 'rack', '~> 2.2.8'

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
